version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./.docker/php
            dockerfile: Dockerfile
        image: consultoria
        container_name: consultoria_app
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            PHP_IDE_CONFIG: "serverName=localhost"
            XDEBUG_CONFIG: "idekey=PHPSTORM"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - consultoria

    db:
        image: mysql:5.7
        container_name: consultoria_db
        restart: always
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_DATABASE}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - consultoria
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: consultoria_phpmyadmin
        ports:
            - "8081:80"
        links:
            - db:db
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_DATABASE}
        networks:
            - consultoria
        depends_on:
            -   db

    nginx:
        build: .docker/nginx
        container_name: consultoria_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/app
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - consultoria


networks:
    consultoria:
        driver: bridge

volumes:
    mysql: {}
    nginx: {}
